name: Python application

on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python_version: 3.7
     
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install project and dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        pip install -r dev-requirements.txt
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
