name: Python application

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.7]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Export path to python executable
      run: echo ::set-env name=PYTHON_EXE::python
    - name: Install project and dependencies
      run: |
        $PYTHON_EXE -m pip install --upgrade pip
        $PYTHON_EXE -m pip install -e .
        $PYTHON_EXE -m pip install -r dev-requirements.txt
        $PYTHON_EXE ci/install_coverage_subprocess_pth.py
    - name: Display Python version
      run: $PYTHON_EXE -c "import sys; print(sys.version)"
    - name: Run linting
      run: |
        # stop the build if there are Python syntax errors or undefined names
        $PYTHON_EXE -m flake8 . --count --verbose --select=E901,E999,F821,F822,F823 \
          --show-source --statistics
        # exit-zero treats all errors as warnings.  The GitHub editor is 127
        # chars wide
        $PYTHON_EXE -m flake8 . --count --exit-zero --max-complexity=10 \
          --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        COVERAGE_PROCESS_START=$GITHUB_WORKSPACE/.coveragerc \
          PYTHONPATH='.:tests' $PYTHON_EXE -m pytest -r s
        coverage combine --append
        coverage xml -i
    - name: Publish coverage results
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  python-nightly-build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[ci python-nightly]')"
    steps:
    - name: Set up Python Nightly
      run: |
        export
        pushd ..
        export VENV_DIR=$PWD/python38
        git clone https://github.com/python/cpython.git
        pushd cpython
        # ./configure
        # make
        python -m venv "$VENV_DIR"
        popd
        popd
        echo ::set-env name=PYTHON_EXE::$VENV_DIR/bin/python
    - name: Install project and dependencies
      run: |
        ls
        $PYTHON_EXE -m pip install --upgrade pip
        $PYTHON_EXE -m pip install -e .
        $PYTHON_EXE -m pip install -r dev-requirements.txt
        $PYTHON_EXE ci/install_coverage_subprocess_pth.py
    - name: Display Python version
      run: $PYTHON_EXE -c "import sys; print(sys.version)"
    - name: Run linting
      run: |
        # stop the build if there are Python syntax errors or undefined names
        $PYTHON_EXE -m flake8 . --count --verbose --select=E901,E999,F821,F822,F823 \
          --show-source --statistics
        # exit-zero treats all errors as warnings.  The GitHub editor is 127
        # chars wide
        $PYTHON_EXE -m flake8 . --count --exit-zero --max-complexity=10 \
          --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        COVERAGE_PROCESS_START=$GITHUB_WORKSPACE/.coveragerc \
          PYTHONPATH='.:tests' $PYTHON_EXE -m pytest -r s
        coverage combine --append
        coverage xml -i
    - name: Publish coverage results
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  distributed-downstream-build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[ci distributed]')"
    env:
      PROJECT: distributed
      TEST_REQUIREMENTS: pytest pytest-timeout numpy pandas mock bokeh fsspec>=0.3.3
      PROJECT_URL: https://github.com/dask/distributed.git
      PYTEST_ADDOPTS: "--timeout-method=thread --timeout=300 -m \"not avoid_travis\" -k \"not test_dask_scheduler and not test_workspace_concurrency and not test_defaults and not test_service_hosts and not test_logging_file_config and not test_hostport and not test_workdir_simple and not test_two_workspaces_in_same_directory and not test_recompute_released_results and not test_connection_args and not test_listen_args and test_cleanup\""  # remove `and test_cleanup` when before merging
    strategy:
      matrix:
        python_version: [3.7]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install project and dependencies
      run: |
        chmod +x ./.github/scripts/install_downstream_project.sh
        ./.github/scripts/install_downstream_project.sh
    - name: Test the downstream project
      run: |
        chmod +x ./.github/scripts/test_downstream_project.sh
        ./.github/scripts/test_downstream_project.sh
  joblib-downstream-build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[ci joblib]')"
    env:
      PROJECT: joblib
      TEST_REQUIREMENTS: "pytest numpy distributed"
      PROJECT_URL: https://github.com/joblib/joblib.git
    strategy:
      matrix:
        python_version: [3.7]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install project and dependencies
      run: |
        chmod +x ./.github/scripts/install_downstream_project.sh
        ./.github/scripts/install_downstream_project.sh
    - name: Vendor current cloudpickle inside joblib
      run: |
        pushd ../joblib/joblib/externals
        source vendor_cloudpickle.sh ../../../cloudpickle
        popd
    - name: Test the downstream project
      run: |
        chmod +x ./.github/scripts/test_downstream_project.sh
        ./.github/scripts/test_downstream_project.sh
  loky-downstream-build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[ci loky]')"
    env:
      PROJECT: loky
      TEST_REQUIREMENTS: "pytest psutil"
      PROJECT_URL: https://github.com/tomMoral/loky.git
    strategy:
      matrix:
        python_version: [3.7]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install project and dependencies
      run: |
        chmod +x ./.github/scripts/install_downstream_project.sh
        ./.github/scripts/install_downstream_project.sh
    - name: Test the downstream project
      run: |
        chmod +x ./.github/scripts/test_downstream_project.sh
        ./.github/scripts/test_downstream_project.sh
  ray-downstream-build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[ci ray]')"
    env:
      PROJECT: ray
    strategy:
      matrix:
        python_version: [3.7]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install project and dependencies
      run: |
        $PYTHON_EXE -m pip install --upgrade -r dev-requirements.txt
        $PYTHON_EXE -m pip install setproctitle psutil ray==0.6.4
        PROJECT_DIR="$($PYTHON_EXE -c "import os, ray; print(os.path.dirname(ray.__file__), flush=True)")"
        rm $PROJECT_DIR/cloudpickle/cloudpickle.py
        cp cloudpickle/cloudpickle.py $PROJECT_DIR/cloudpickle/cloudpickle.py
    - name: Test the downstream project
      run: |
        PROJECT_DIR="$($PYTHON_EXE -c "import os, ray; print(os.path.dirname(ray.__file__), flush=True)")"
        COVERAGE_PROCESS_START="$TRAVIS_BUILD_DIR/.coveragerc" PYTHONPATH='.:tests' pytest -r s
        pytest -vl $PROJECT_DIR/tests/test_basic.py::test_simple_serialization
        pytest -vl $PROJECT_DIR/tests/test_basic.py::test_complex_serialization
        pytest -vl $PROJECT_DIR/tests/test_basic.py::test_ray_recursive_objects
        pytest -vl $PROJECT_DIR/tests/test_basic.py::test_serialization_final_fallback
        pytest -vl $PROJECT_DIR/tests/test_recursion.py
